services:

  ansible:
    image: docker.io/mathieued/ansible_base
    command: ansible --version
    volumes:
      - ./ansible:/var/ansible:rw

  postgresql:
    image: docker.io/bitnami/postgresql:16
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    env_file: env/postgresql.env

  redis:
    image: docker.io/bitnami/redis:7.0
    volumes:
      - 'redis_data:/bitnami'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes

  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:2
    env_file: env/airflow_sch_wrk.env

  airflow-worker:
    image: docker.io/bitnami/airflow-worker:2
    env_file: env/airflow_sch_wrk.env

  airflow:
    image: docker.io/bitnami/airflow:2
    env_file: env/airflow_websrv.env
    ports:
      - '8080:8080'

  semaphore:
    ports:
      - 3000:3000
    image: docker.io/semaphoreui/semaphore:latest
    env_file: env/semaphore.env
    volumes:
      # - '${PWD}/semaphore/config.json:/etc/semaphore/config.json'
      # - 'semaphore_db:/var/lib/semaphore'
      - ./semaphore/database:/var/lib/semaphore
      - ./ansible:/home/semaphore/ansible:rw

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  ansible_playbooks:
    driver: local
  ansible_inventories:
    driver: local
  semaphore_db:
    driver: local